#!/usr/bin/env python3
"""Merge the TSO package + kernel driver into ONE self-contained file.

Kaggle's CLI uploads only the kernel's code_file, so a multi-module package
never reaches the kernel. This script inlines the modules in dependency order
(stripping relative imports) and appends the driver, producing
``kaggle_kernel_tso/main.py`` that runs standalone on Kaggle.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tso")
DRIVER = os.path.join(ROOT, "kaggle_kernel_tso", "driver_main.py")
OUT = os.path.join(ROOT, "kaggle_kernel_tso", "main.py")

# module -> the `from .x import ...` lines it needs (stripped; names come from
# the merged namespace). Order = dependency order.
MODULES = [
    "attractors",   # np only
    "embedding",    # np only
    "koopman",      # np only
    "pipeline",     # embedding, koopman
    "neural_field", # torch
    "train_loop",   # torch
    "bifurcation",  # attractors, embedding, pipeline
    "deep_koopman", # pipeline, embedding, koopman
    "foundation",   # embedding, pipeline, bifurcation
    "viz",          # np, matplotlib
]

REL_IMPORT = re.compile(r"^\s*from\s+\.{1,2}\S*\s+import\s+.*$")


def load(name):
    with open(os.path.join(SRC, name + ".py"), encoding="utf-8") as fh:
        return fh.read()


def main():
    parts = [
        '"""TSO foundation pretraining — Kaggle GPU kernel (self-contained).',
        "Generated by scripts/build_kernel_single.py from the tso package.",
        '"""',
        "from __future__ import annotations",
    ]
    for name in MODULES:
        code = load(name)
        lines = [ln for ln in code.splitlines()
                 if not REL_IMPORT.match(ln)
                 and not ln.strip().startswith("from __future__ import")]
        # drop the module-level docstring (keeps the merged file readable)
        text = "\n".join(lines).strip()
        if text.startswith('"""'):
            end = text.find('"""', 3)
            if end != -1:
                text = text[end + 3:].lstrip("\n")
        parts.append(f"\n# ===================== module: {name} =====================\n")
        parts.append(text)

    with open(DRIVER, encoding="utf-8") as fh:
        parts.append("\n# ===================== kernel driver =====================\n")
        parts.append(fh.read())

    merged = "\n".join(parts) + "\n"
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(merged)
    print(f"wrote {OUT} ({len(merged.splitlines())} lines)")
    # sanity: no real `from tso ... import` statements may remain
    if re.search(r"^from\s+tso\s+import", merged, re.M):
        raise SystemExit("driver still imports tso package!")
    print("OK: no `from tso import` statements remain")


if __name__ == "__main__":
    sys.exit(main())
